backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "programs"
    label: 'Programs'
    folder: "src/pages/programs"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "program"}
      - {label: Title, name: title, widget: string}
      - {label: "Subtitle", name: subTitle, widget: string}
      - label: Categories
        name: categories
        widget: list
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Image, name: image, widget: image}
      - label: Staff
        name: Staff
        widget: list
        fields:
          - {label: "Staff Member", name: staffMember, widget: relation, collection: staff, searchFields: ['name'], valueField: 'name'}

  - name: "staff"
    label: "Staff"
    folder: "/src/collections/staff"
    create: true
    fields:
      - {label: "Name", name: name, widget: string}
      - {label: "Title", name: title, widget: string}
      - {label: "Description", name: description, widget: text, required: false}
      - {label: "Image", name: image, widget: image, required: false}
      - label: Achievements
        name: achievements
        widget: list
        required: false
        fields:
          - {label: Achievement, name: achievement, widget: string, required: false}